name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build and push Docker image
        run: |
          docker build -t marcossuntaxi/frontend:latest .
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push marcossuntaxi/frontend:latest

      - name: Deploy to EC2
        run: |
          echo "${{ secrets.AWS_SSH_KEY }}" > /tmp/key.pem
          chmod 400 /tmp/key.pem
          
          ssh -o StrictHostKeyChecking=no -i /tmp/key.pem ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} << 'EOF'
            set -e
            
            # Actualizar el contenedor con la última imagen
            docker pull marcossuntaxi/frontend:latest

            # Ir al directorio del proyecto (ajusta según sea necesario)
            cd /home/${{ secrets.AWS_USER }}/app

            # Actualizar y reiniciar los servicios
            docker-compose down
            docker-compose up -d --remove-orphans

            exit
          EOF

      - name: Clean up
        run: rm -f /tmp/key.pem
